### ISSUE TITLE
Not working with repo with 20k forks

### ISSUE THREAD

**Issue by Cosmoledo** [AndreMiras/gitpop3#14]
Hey, I have tried your tool with _https://github.com/nodejs/node_. This repo has 20k forks and it seems that gitpop3 crashes, gitpop2 does not have this problem. I know this is an extreme test, but a small error nonetheless. ;) The screen gets pure white and following error message gets printed into the console:
![grafik](https://user-images.githubusercontent.com/26510897/117647056-c98e0e00-b18c-11eb-847a-6c92190cbe6b.png)

**Comment by AndreMiras** [comment]
Hey @Cosmoledo thanks for the report, I eventually took time to look it up and fix it
![image](https://user-images.githubusercontent.com/24973/152979886-713cafa5-78a0-496e-bc25-a1d8d9199baa.png)
